// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTOwg89ATH2aIvalE07I3RN-7blOzcAe8',
    appId: '1:13155329729:web:edb9ead47d6b70623c1640',
    messagingSenderId: '13155329729',
    projectId: 'online-shopping-3dd08',
    authDomain: 'online-shopping-3dd08.firebaseapp.com',
    storageBucket: 'online-shopping-3dd08.firebasestorage.app',
    measurementId: 'G-BSK71MT8H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu19wyK2GKbIzf4Htiflhu1tqRwvUdhU4',
    appId: '1:13155329729:android:4c3a257d1a3f7cc13c1640',
    messagingSenderId: '13155329729',
    projectId: 'online-shopping-3dd08',
    storageBucket: 'online-shopping-3dd08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaQp6mtXL4SoVOg44mxA369Oh_8j4JW58',
    appId: '1:13155329729:ios:a816c8e860c299aa3c1640',
    messagingSenderId: '13155329729',
    projectId: 'online-shopping-3dd08',
    storageBucket: 'online-shopping-3dd08.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTOwg89ATH2aIvalE07I3RN-7blOzcAe8',
    appId: '1:13155329729:web:8b483248bc76023d3c1640',
    messagingSenderId: '13155329729',
    projectId: 'online-shopping-3dd08',
    authDomain: 'online-shopping-3dd08.firebaseapp.com',
    storageBucket: 'online-shopping-3dd08.firebasestorage.app',
    measurementId: 'G-36L8GM9YDM',
  );
}
